### ISSUE TITLE
Documentation link is dead

### ISSUE THREAD

**Issue by mcclearyj** [astromatic/swarp#9]
Hello, 

I tried to access the documentation for SWarp on the Astromatic website, but the link appears to be dead (404 error). Is there a more up-to-date location?

Thank you!

**Comment by ebertin** [comment]
Thanks for the heads up. Yes sorry. I have upgraded the AstrOmatic server and got rid of the old SVN. However not is functional yet and the new Sphinx doc is not yet available. Meanwhile I have fixed the link. You can find it [there](https://raw.githubusercontent.com/astromatic/swarp/legacy_doc/prevdoc/swarp.pdf).
